import machine
import utime
red=machine.Pin(2,machine.Pin.OUT)
yellow=machine.Pin(4,machine.Pin.OUT)
green=machine.Pin(5 ,machine.Pin.OUT)
buzzer=machine.Pin(19,machine.Pin.OUT)
while(True):
    red.on()
    print("Red is ON")
    utime.sleep(1)
    red.off()
    yellow.on()
    print("Yellow is ON")
    utime.sleep(1)
    yellow.off()
    green.on()
    print("Green is ON")
    utime.sleep(1)
    green.off()
    buzzer.on()
    print("Buzzer is ON")
    utime.sleep(1)
    buzzer.off()
    green.on()
    print("Green is ON")
    utime.sleep(1)
    green.off()
    yellow.on()
    print("Yellow is ON")
    utime.sleep(1)
    yellow.off()
    red.on()
    print("Red is ON")
    utime.sleep(1)
    red.off()
    buzzer.on()
    print("Buzzer is ON")
    utime.sleep(1)
    buzzer.off()


    